global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']
        labels:
          service: 'otel-collector'

  - job_name: 'otel-query'
    static_configs:
      - targets: ['otel-query:9091']
        labels:
          service: 'otel-query'
